---
title: "Harvard Course Enrollment"
author: "Dasha Metropolitansky"
date: "April 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(fs)

# Downloading enrollment data for Spring 2019 from Registrar's Office website

download.file(url = "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19.xlsx",
              destfile = "reg_2019.xlsx",
              mode = "wb")

# Downloading enrollment data for Spring 2018 from Registrar's Office website

download.file(url = "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_03.06.18.xlsx",
              destfile = "reg_2018.xlsx",
              mode = "wb")

# Reading in the Spring 2019 and 2018 enrollment data, cleaning the variable names, filtering out cases where the course name is not listed, and selecting only the course ID, undergraduate enrollment totals, and course department variables

spring_2019 = read_excel("reg_2019.xlsx", skip = 3) %>% 
  clean_names() %>%
  filter(!is.na(course_name)) %>%
  select(course_id, u_grad, course_department)
  
spring_2018 = read_excel("reg_2018.xlsx", skip = 3) %>% 
  clean_names() %>%
  filter(!is.na(course_name)) %>%
  select(course_id, u_grad, course_department)

# Deleting the files to clear up space and prevent duplicate downloads if running the code more than once

file_delete(c("reg_2018.xlsx", "reg_2019.xlsx")) 
```

```{r include = FALSE}

# Joining the Spring 2019 and Spring 2018 data by course ID

x = spring_2019 %>%
  left_join(spring_2018, by = "course_id") %>%
  
# Subsetting the joint dataset for courses that were offered in the same department in both years
  
  filter(course_department.x == course_department.y) %>%
  
# Removing duplicate columns from the join
  
  select(-course_department.y) %>%
  
# Renaming the undergraduate enrollment variables to indicate which year they refer to 
  
  rename(course_department = course_department.x,
         u_grad_2019 = u_grad.x, 
         u_grad_2018 = u_grad.y) %>%
  
# Renaming departments to be concise and consistent
  
  mutate(course_department = recode_factor(course_department,
                                           `African & African Amer Studies` = "African Studies",
                                           `Classics, The` = "Classics",
                                           `Celtic Languages & Literatures` = "Celtic Languages",
                                           `East Asian Langs & Civ` = "East Asian Languages",
                                           `Envi Science & Public Policy` = "Environmental Science",
                                           `Germanic Languages & Lit` = "Germanic Languages",
                                           `Near Eastern Languages & Civ` = "Near Eastern Languages",
                                           `Organismic & Evolutionary Biol` = "Organismic & Evolutionary Biology",
                                           `Religion, The Study of` = "Religion",
                                           `Romance Languages & Lit` = "Romance Languages",
                                           `Slavic Languages & Literatures` = "Slavic Languages",
                                           `Stem Cell & Regenerative Biol` = "Regenerative Biology")) %>%
  
# Grouping by department and calculating the total number of students who took classes in each department by year 
  
  group_by(course_department) %>%
  
  summarise(department_total_19 = sum(u_grad_2019),
            department_total_18 = sum(u_grad_2018)) %>%

# Filtering for departments where the total number of students enrolled in their courses is greater than 50 in both 2018 and 2019
# I included this filter because it seems disingenuous to include a department with a very small number of students (i.e. an increase from 5 to 10 students is a 100% increase)
  
  filter(!(department_total_19 <50 | department_total_18 <50)) %>%
  
# Creating a new variable for the percent change in enrollment from Spring 2018 - Spring 2019 and arranging in descending order of percent change in enrollment 
  
  mutate(percent_change = round(((department_total_19 - department_total_18)/department_total_18 * 100), digits = 0)) %>%
  arrange(desc(percent_change))

# Selecting the top 8 and bottom 8 results (greatest percent increase in enrollment, greateset percent decrease in enrollment)
# I chose 8 because selecting any more entries makes the graph too cluttered 

x_top = x %>%
  slice(1:8)

x_bottom = x %>%
  slice(tail(row_number(), 8))

# Binding together the top 8 and bottom 8 results into a new dataframe

y = rbind(x_top, x_bottom)
  
```

```{r echo = FALSE}

# Creating a bar plot with department on the x-axis (in ascending order by percent change in enrollment) and percent change in enrollment on the y-axis
# The colour of the bars corresponds to the size of the department (total number of students enrolled in its courses) in 2019

y %>%
  ggplot(aes(x = reorder(course_department, percent_change), y = percent_change, fill = department_total_19)) +
  geom_col() +
  
# Flipping the coordinates so that the departments are listed on the y-axis
# I did this to improve the readability of the graph: when the departments are on the x-axis, they are too packed together. 
  
  coord_flip() + 

# Adding a solid vertical line at the 0% change in enrollment mark and a dashed horizontal line that delineates between the top and bottom 8 departments
  
  geom_hline(yintercept = 0, colour = "black", size = 0.5) +
  geom_vline(xintercept = 8.5, colour = "black", linetype = "dotted") +

# Filling in the top and bottom halves of the graph with different colours to further delineate between the top and bottom departments
  
  geom_rect(aes(xmin = 8.5, xmax = 16.5, ymin = -Inf, ymax = Inf), alpha = 0.015, fill = "steelblue2") +
  geom_rect(aes(xmin = 0, xmax = 8.5, ymin = -Inf, ymax = Inf), alpha = 0.015, fill = "dodgerblue4") +

# Changing the axis labels and adding a caption, title, and subtitle
  
  labs(y = "Percent Change in Course Enrollment",
       x = "Department",
       caption = "\n *Departments in which 50+ students took courses for Spring 2018 and 2019
       \n **The total number of students enrolled in all courses offered by the department in Spring 2019
       \n Data from the Harvard Registrar",
       title = "Changing Popularity of Harvard Courses by Department",
       subtitle = "Undergraduate enrollment in Spring 2018 vs. Spring 2019*") +

  # Changing the limits of the x-axis scale to be from -60 to 60
  
  ylim(-60, 60) +
  
  # Applying the minimal theme to the graph
  
  theme_minimal() +
  
  # Changing the legend title text
  
  guides(fill = guide_legend(title= "Department Size**")) +
  
  #Adding spaces between the axes labels, title, subtitle and the plot
  
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0))) +
  theme(plot.title = element_text(face="bold", margin = margin(t = 0, r = 0, b = 9, l = 0))) +
  theme(plot.subtitle = element_text(margin = margin(t = 0, r = 0, b = 9, l = 0)))
```

